### ISSUE TITLE
Tags not handed down by task list plugin in 0.66

### ISSUE THREAD

**Issue by stewit** [jaap-karssenberg/zim-desktop-wiki#101]
Hello,
first of all: Thanks for ZIM and the efforts you put into it to improve it even further! It's a great tool which really helps me to organize myself everyday!

Now to my issue: After the recent update to 0.66 I discovered the following behaviour of the task list plugin:

Version 0.66 of ZIMs task list plugin does not apply a tag after a "TODO:" to the tasks in subsequent lines anymore as is described at the end of http://zim-wiki.org/manual/Plugins/Task_List.html .

The basic example shown there does not work for me anymore. I have attached a screenshot showing the behaviour together with my task list plugin configuration window opened:

![grafik](https://user-images.githubusercontent.com/16646123/26969218-42dba7f4-4d05-11e7-80ab-bf80215bcd8e.png)

Also I have a question concerning the changes in 0.66 regarding the drop of the "Next:" labels for tasks which sequentially depend on each other. Is there an intended replacement for a longer list of tasks that have to be completed one after the other?

**Comment by jaap-karssenberg** [comment]
It does apply the tag, but the search function did not work correctly for this case - fixed in 47532625cbfbf738070e77d2fa1abfea6896e73d

My thinking about sequential lists is that you might just as well use a bullet list and change the next bullet to a task when needed. Or use tasks that are closed ([x]) and open them when needed.

Probably it can be more sophisticated, but added a "NEXT" label on each line seems the wrong way to me.
