### ISSUE TITLE
"Jump to" has become very time consuming job

### ISSUE THREAD

**Issue by Kiwon** [jaap-karssenberg/zim-desktop-wiki#182]
I recently has updated zim from '0.64' to '0.67' on 'Linux Mint'

really like it new things such as "Inserting Horizontal Line"

But the thing is when I search some note via "Jump to", It is taking much more time than before.

I'm afraid that I don't have enough skill to find out what the problem is from source code.

I hope that you can figure it out!

"Zim" is the best note that I have used before!

**Comment by jaap-karssenberg** [comment]
For sure there is room for imrpovement, but in my testing I don't notice big delays.

Do you have more specific, e.g. about the size of your notebook, number of potential matches?

**Comment by Osndok** [comment]
There is no doubt that the auto-completion menu building is a bottleneck that slowly chokes out (performance-wise) as the number of pages (or links?) in a notebook increases.

I tried to tackle this not too long ago:
* https://github.com/jaap-karssenberg/zim-desktop-wiki/pull/121
* https://github.com/Osndok/zim-desktop-wiki/tree/insertlink-faster

...and the performance is *worlds* better, but after using it long term I can say that it is still not "correct". I suppose it is good enough that I have not found time to further improve it.

**Comment by nasedil** [comment]
Yes indeed it may be very slow.  In my notebook which I use every day and insert links at least hundred times per day, I have to wait significant time until the auto-complete list populates.

It seems that both number of pages in the notebook and the number of pages on the current pages pay a role in the delay.

It also felt like it was faster in older versions, until an update that happened between 1 or 2 years ago.

I think I would try to work on the problem, since it significantly affects me.  @Osndok you are saying your fork is not completely correct -- can you elaborate what is not working correctly there?

**Comment by nasedil** [comment]
Oh, thanks @Osndok!  I should try a master branch then.  Somehow didn't think of it before.

**Comment by jaap-karssenberg** [comment]
I believe this to be fixed in the latest release. Please open a new ticket if similar behavior seen with zim 0.69 or newer.
