### ISSUE TITLE
Link indexing needs to treat underscore as whitespace

### ISSUE THREAD

**Issue by jaap-karssenberg** [jaap-karssenberg/zim-desktop-wiki#183]
Links that contain a "\_" will result in a placeholder in the index, even if the page (with a space instead of the "\_") exists.

See https://bugs.launchpad.net/zim/+bug/1710104 for test data

**Comment by fdt-dev** [comment]
Since I sort of tripped over the same issue I found this bugreport.
Have you considered treating links containing a "_" as different files than links with a space? For example in a modern filesystem it would be perfectly valid to have these two files alongside in the same folder:
"file 1.txt"
"file_1.txt"
They'd be different files and for that reason I think Zim should also treat both as different files and links respectively. (I know: it is not particularly likely that someone would actually use that scenario, but to prevent future issues, I think it'd be best to cover it.)

**Comment by purejava** [comment]
The problem for me arose, as I created the pages in my notebook with zim <0.66 like [this](https://bugs.launchpad.net/zim/+bug/1710104/+attachment/4930570/+files/nice.zip) example.
Opening it with the current zim 67.1 triggers re-indexing and leads to the problem shown in the screenshot.

The page was originally created as "Spezielle Themen" and gets doubled.


![zim](https://user-images.githubusercontent.com/1822238/34485566-a0d09d2e-efcb-11e7-8b4b-1209278708e5.png)
