### ISSUE TITLE
Zim clobbers files instead of updating them

### ISSUE THREAD

**Issue by ipsod** [jaap-karssenberg/zim-desktop-wiki#188]
This unexpected behavior breaks at least two filesystem features: hardlinks and extended file attributes.

I'll describe below what I'm seeing in Linux Mint 18 KDE with Zim 0.67.

## Hardlinks
Create a hardlink:
```
$ touch Note.txt
$ ln Note.txt NoteCopy.txt
$ ls -i Note*
   6171990 Note.txt  6171990 NoteCopy.txt  # file id's match
```

After editing and saving `Note.txt` from inside of Zim:
```
$ ls -i Note*
6172673 Note.txt  6171990 NoteCopy.txt  # file id's no longer match
```

After editing `NoteCopy.txt` from inside of Zim:
```
$ ls -i Note*
6172673 Note.txt  6172671 NoteCopy.txt  # neither file id is the same as starting out
```

## Extended file attributes
Set extended attribute on file and confirm that it is set:
```
$ setfattr -n user.whatever -v hello Note.txt
$ getfattr -n user.whatever Note.txt
# file: Note.txt
user.whatever="hello"
```

After editing and saving file from inside of Zim:
```
$ getfattr -n user.whatever Note.txt
Note.txt: user.whatever: No such attribute
```

**Comment by jaap-karssenberg** [comment]
This happens because zim first writes to a temporary file and then uses "`mv`" to do an atomic replace of the target file. This way we avoid any risk of files left truncated on errors while writing.

Yes this breaks hardlinking, but I'm not sure I would want to support hardlinking for a desktop application like zim.

No experience with extended attributes, maybe we need to ensure the temporary file gets the same attributes as the target file before the replace.

**Comment by jaap-karssenberg** [comment]
Closing this item for now as I don't see the benefit of supporting hard links and extended attributes
