### ISSUE TITLE
style.conf on windows

### ISSUE THREAD

**Issue by FlorianWanders** [jaap-karssenberg/zim-desktop-wiki#218]
To apply changes from `style.conf`, the [manual ](http://zim-wiki.org/manual/Help/Config_Files.html) instructs to "copy /usr/share/zim/style.conf to ~/.config/zim/". However I am not sure what this means for Windows. I also posted [on superuser](https://superuser.com/q/1260661/534265) with an example. 

And not to forget: Thank you so much for this great app!

**Comment by raphaeldore** [comment]
For me, I placed my custom `style.conf` to `C:\Users\Raphael\AppData\Roaming\zim\config\zim\profiles\Notes\style.conf`.

**Comment by FlorianWanders** [comment]
This did not work for me, but placing it under C:\Users\usr\AppData\Roaming\zim\config\zim did the trick. Thanks for pointing me there!

**Comment by kklepper** [comment]
Sorry, this does not work on my machine. I even renamed `C:\Users\USERNAME\AppData\Roaming\zim\config\zim\style.conf`  without any effect. No `profiles\Notes` here. Clueless. My Zim resides in `D:\data\programs\tools\ZimDesktopWikiPortable` which has tons of subdirectories but none refers to style. 

I work with Zim since 2019 and I am still enthusiastic about it. It would be nice if I could get rid of the underline in h1, though. That "feature" just sucks aesthetically.

**Comment by kklepper** [comment]
Version 0.73.5  portable

**Comment by jaap-karssenberg** [comment]
I don't understand what what you mean by "workplace" so hard for me to
follow what you struggle with.

My recommendation would be not to modify the "environ.ini" unless you have
a good reason for it.

In the default version XDG_CONFIG_HOME is set to "../config"

Assuming you installed the application in
"D:\data\Programme\Tools\ZimDesktopWikiPortable\config\"
this means  the style config should be located at D:\data\Programme\Tools\
config\zim\style.conf

Regards,

Jaap
