### ISSUE TITLE
it's not possible to place tag with two or more words

### ISSUE THREAD

**Issue by InputError** [jaap-karssenberg/zim-desktop-wiki#236]
look at the picture below:
![zim_2017-11-25_06-36-46](https://user-images.githubusercontent.com/23272814/33227016-316f8118-d192-11e7-9ad0-a2a4e8b54906.png)
it's not possible to use several words in tag, is it bug or feature?

I need use tags which always contains more the one word. Now if we will try to press "space" button - tag marks as completed and I see no ways to fix that.

**Comment by Osndok** [comment]
While not authoritative, I would say that this is more of a feature (or more technically, a design constraint) than a bug.

Tags are meant to expedite searching, and (while it is a bit unclear because of the contrived example case) you might be better of with links (and page names *can* have spaces)... even if it's a link to a page that is never created, because the back-links are valuable.

Tags are treated much like a programming identifier, so the customary solution is to use [camelcase](https://en.wikipedia.org/wiki/Camel_case) on word boundaries.

So, for the given example, 'tagWithSeveralWords' might suffice... but I suspect that any more than two words is probably an indicator that you are using this feature outside of its original intent. Which is okay!... but.... thar be dragons, growing pains, etc.

**Comment by InputError** [comment]
@Osndok thanks a lot for so fast reply. My goal to create card-index, there should be many records and each record have several tags, each tag contains several words. I need something to find analogues to any record, tags approach looks the most convenient for that task.

I hope official programmers of ZIM will clear about this issue, is it possible to store several tags or not.

**Comment by Osndok** [comment]
Without a concrete example or analog, it is hard to make a recommendation. However, it still sounds like page links might be a better option than tags.

In Zim, a tag is much like a hashtag; it does not contain any extra data beyond itself... and it sounds like you want to use it as a field in an abstract database.

You said "card index", so let me briefly describe how page-links can be fashioned into a key-value (or field-value) indexing system... suppose you have one record to index, you place it into a well-named page, in this example ":President:Trump".

The contents of this page is simply a list of page links & tags:
* :FirstName:Donald
* :LastName:Trump
* :Born:1946
* +Number:45
* `@Person` (a tag, describing what this record 'is')

Now, I can find that one "record" through any one of those fields, because (even though there is no real page there) I can traverse the backlinks.

Also, notice the tag, which will greatly accelerate a search, such as: `@Person Name:Donald`

Does that sound like what you are trying to accomplish?

**Comment by jaap-karssenberg** [comment]
Tags have to consist of a single word. This is a limitation of the wiki syntax used. The most wiki thing to do would be to use something like "@tagWithSeveralWords"

Probably a good card index would use a mix of notebook hierarchy, links and tags

With hierarchy I mean using sub-pages to file notes. A card can only be in one place in the hierarchy, so keep it simple, e.g. "Persons" are "Places" good divisions because they are orthogonal.

Tags are good for a "many to many" relation, e.g. to classify notes under different topics. 

Links are the right thing for one to one relations, e.g. referring directly to another note.

**Comment by HalMorris** [comment]
There are many great things about Zim, which is why I'm using it, but this is a drawback.

If I want a tag for "Middle East", I must write MiddleEast in my text?  Then there are peoples' names which usually have more than one word.

It's nice to be able to create tags on the fly as you're writing text, with an '@', but what about looking at a page and wanting to tag it "social epistemology" because that is the subject, even if the phrase doesn't appear? (not to mention it's two words).  Most tag systems I'm aware can treat tags as a **page attribute**.  It would help to have that kind of tag.  I suppose we can improvise, and put a "TAGS" section at the bottom of a page, but what if it's a page you copied from somewhere, and don't want to modify?

At some point, when I know the system better, I may **suggest** a solution, but I'm nowhere near ready to do that yet.  I imagine for the time being I will make a convention of adding a "tags" section to my pages, and there I'd be less reluctant to use CamelCase, and probably, for people's names it will be best to use the convention LastnameFirstname.  I guess underlines can be used, as in @Middle_East.
