### ISSUE TITLE
singlefile html  command line option "-s"  to export zim page to single html page is not working*

### ISSUE THREAD

**Issue by rdft4e** [jaap-karssenberg/zim-desktop-wiki#244]
There is no problem creating a single html file export of a full notebook using Zim 0.65 GUI:

File -> export -> complete notebook -> Forward -> format: html -> template: ZeroFiveEight -> Forward
-> Export all pages to a single file -> exported_file.html

However, using the command line to export one html file as above, for example:

zim --export -s -O --template=ZeroFiveEight -o OUTPUTDIRECTORY NOTEBOOK

it generates a no single file html export, it generates html files and folders.

I think that the '-s' option is not working in command line mode.

*This bug was also reported in the launchpad webpage. https://bugs.launchpad.net/zim/+bug/1701418

**Comment by rdft4e** [comment]
Hi, I have tried Zim 0.67 and 0.67-rc2 (alldeb type packages) and the bug still persists but probably it is because the 0.67 version does not include this bug fix yet?
On the other hand, i have tried by downloading this git folder but I can not install because gobject dependencies and I do not know how check a command line type export without true zim installation.

Please, could you confirm that 0.67 or 0.67-rc2 deb packages included this bug fix? If not, could you upload a deball package with this bug fix? (no hurry)

**Comment by jaap-karssenberg** [comment]
As you can see above, this issue was closed just 11 hours ago with a patch in the main branch. So it could not possibly be fixed in a release that is made almost 6 months ago.

All fixes will be part of next release.

**Comment by orc-oist** [comment]
Yes, I know that the bug fix was just solved. I opened the issue, first in launchpad and later here in github and I was emailed when you closed the issue. I thank you overall for Zim, i use it in a daily basis and I thank you also for this bug fix. Currently, the workaround that I have to do to overcome it is crazy and dirty and it is because I am so expecting about this bug fix. 

Please, let me ask you two questions related to this,

1) I can run this github main branch version of zim without problems by using ./zim.py. However, there are dependency problems when I try to install it. It is my fault because my computer is a mess of mixed python things installed using condas and minicondas and python things installed using the repositories of my distribution or another things using pip. The question is: Is it possible to run the command line version of this github zim main branch without installation (only test mode) to export a notebook as a single html file?. Overall, the idea is to use 0.67 as a GUI as usual but to use this github-zim version for my unattended nightly single file exporting procedure. I know that it is still dirty but at least it is not crazy.

2) When the next release is scheduled?

**Comment by rdft4e** [comment]
Yes, I know that the bug fix was just solved. I opened the issue, first in launchpad and later here in github and I was emailed when you closed the issue. I thank you overall for Zim, i use it in a daily basis and I thank you also for this bug fix. Currently, the workaround that I have to do to overcome it is crazy and dirty and it is because I am so expecting about this bug fix. 

Please, let me ask you two questions related to this,

1) I can run this github main branch version of zim without problems by using ./zim.py. However, there are dependency problems when I try to install it. It is my fault because my computer is a mess of mixed python things installed using condas and minicondas and python things installed using the repositories of my distribution or another things using pip. The question is: Is it possible to run the command line version of this github zim main branch without installation (only test mode) to export a notebook as a single html file?. Overall, the idea is to use 0.67 as a GUI as usual but to use this github-zim version for my unattended nightly single file exporting procedure. I know that it is still dirty but at least it is not crazy.

2) When the next release is scheduled?

**Comment by rdft4e** [comment]
Hi,
finally I have installed the zim 0.68-1 version from the debian sid repository (via dpkg -i). Now the command line "export to single html file" works as expected. Thank you very much for Zim

best regards
