### ISSUE TITLE
separate style document to apply this to all the pages

### ISSUE THREAD

**Issue by jhojen26** [jaap-karssenberg/zim-desktop-wiki#254]
How to apply a style document for all pages, when exporting to html the style is inside each document. I want to have a single style that applies to all html documents.

thank you very much

**Comment by Osndok** [comment]
Please don't open duplicates like #255, especially when asking for help (this is really meant more for bug/feature tracking).

The simple answer is that you want to use a different "TEMPLATE"... feel free to copy/modify one of the existing templates for your custom style, or follow the link that says "get more templates" to browse other community-contributed templates.

Do you have any more questions?

![zim-export-5a2a110c](https://user-images.githubusercontent.com/80066/33750854-5c2e632e-db9c-11e7-9213-5781c5cd8422.png)

**Comment by jhojen26** [comment]
thanks for answering.

I think there are two things.

https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/255 one has to do with the server that has, I want to be able to select a template that I create.
![screenshot_20171208_065319](https://user-images.githubusercontent.com/24486935/33765624-bf179a64-dbe7-11e7-958a-964e4d71740a.png)
![screenshot_20171208_0658133](https://user-images.githubusercontent.com/24486935/33765625-c136568c-dbe7-11e7-8efb-71ddb1cabc7e.png)

I create a template, but I do not know how to put the style outside the html, when I have many pages use only one style.
![screenshot_20171208_0657091](https://user-images.githubusercontent.com/24486935/33765514-28928054-dbe7-11e7-9e98-ff05e18c871f.png)
![screenshot_20171208_0657362](https://user-images.githubusercontent.com/24486935/33765516-2b0055d2-dbe7-11e7-8647-a830c6e230ec.png)

**Comment by Osndok** [comment]
Thank you for the clarification, it seems like one of two things is happening for this (the first) issue...

Either you need help with really-basic html:
* https://www.w3schools.com/Tags/tag_link.asp
* http://www.htmlhelp.com/reference/css/style-html.html

Or... assuming that you know how to do know how to create CSS stylesheet links... I imagine that the real issue here is that the zim export/template system currently does not have any form of relative CSS linking that would make this sort of linking easy.

However, you have several options:
* make your template use an absolute link; it will be broken when viewed locally, but it will work on the server
* make your template use a remote css file; it will work when viewed locally & on a server, but is no longer 'self contained' (requires internet access).
* go ahead and use a relative link, but either:
    * restrict yourself to root-level pages,
    * copy (or link) the style.css into every directory created, or
    * "post process" the export to add the right number of '../' for the directory depth.
