### ISSUE TITLE
style.conf in windows portable installation

### ISSUE THREAD

**Issue by freyana** [jaap-karssenberg/zim-desktop-wiki#257]
Hi,

Great tool, I greatly appreciate you work!

Where do I need to put my changed style.conf in a Windows portable installation?
Original style.conf files are available at:
- \App\ZimDesktopWiki
- \App\Config
- \App\ZimDesktopWiki\share

Thanks, Freyana

**Comment by jaap-karssenberg** [comment]
@bkidwell probably you can answer better than I can

**Comment by mystyc** [comment]
I have my altered style.conf in `App\Config\zim` for Zim portable v0.67 on windows.  
The default style.conf files are located in a few other areas, but I usually let them remain since they seem to be ignored.  For me, this includes the version kept in the `\App\ZimDesktopWiki\share\zim` folder, and another in `\App\ZimDesktopWiki\data`.

**Comment by freyana** [comment]
Thanks, changing \App\Config\zim\style.conf worked :-)
