### ISSUE TITLE
Не работает сочетание клавиш "Ctrl +C" 

### ISSUE THREAD

**Issue by it19862** [jaap-karssenberg/zim-desktop-wiki#282]
Не работает сочетание клавиш "Ctrl +C"

**Comment by banan314** [comment]
For those who don't know :ru:. If you run the application from terminal, hitting `Ctrl+C` doesn't work (which means nothing happens). :link: [The issue is described on StackOverflow](https://stackoverflow.com/questions/16410852/keyboard-interrupt-with-with-python-gtk).

Please see my PR #288. It solves the problem on Ubuntu, as after running `./zim.py` I can terminate using `^C`.

**Comment by jaap-karssenberg** [comment]
Just tested here, but even without your patch `^C` works fine for me.

**Comment by banan314** [comment]
I just cloned the repository and wrote 
```
./zim.py
```
No window appeared and `^C` didn't work. Then I wrote `./setup.py build`. Afterward `^C` worked.

But today I cannot reproduce it as well, even checking out the commit it was the day I opened the issue.

**Comment by sojusnik** [comment]
Is this somehow connected to https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/81?

**Comment by genodeftest** [comment]
@sojusnik : #81 is probably not related as I see the issue with a different (latin) keyboard layout. Also, #81 is about GUI shortcuts whereas this happens on the console.

**Comment by sojusnik** [comment]
@genodeftest Thanks for pointing that out.

**Comment by Sandman44** [comment]
That simple:
Edit - Preferences - Editing - Default format for copying text to the clopboard  -change from Text to Wiki!

**Comment by jaap-karssenberg** [comment]
This discussion is confusing "^C" in the application for copy-paste and "^C" in the terminal for killing the process.

Current master branch both work correctly.
