### ISSUE TITLE
Easier way to resize images

### ISSUE THREAD

**Issue by synchr** [jaap-karssenberg/zim-desktop-wiki#318]
The current way of resizing images takes a lot of time, especially if multiple images have to be resized and the fact that you are not able to see new size before closing the "Edit image" menu.

I have some suggestions to improve image resizing:

- Add shortcuts to resize image by a fixed amount (bigger or smaller), this shortcut could be pressed repeatedly until the desired size is reached 
- Word/LibreOffice like resizing where you can drag the corners of the image

Both these suggestions require you to be able to "select" the image. It's actually possible right now to "select" the image by dragging the mouse from the side of the image while holder down left mouse button, like when selecting text, but for the above suggestions to work properbly the user should be able to "select" the image by just left clicking on it.

I know that these features might be complicated to implement, but i think that easier image resizing would improve the workflow a lot when handling images.

Maybe somebody else have a better suggestion that would be easier to implement?

**Comment by synchr** [comment]
Maybe the shortcut to resize images could resize the image that is beside the cursor. This seems a little hackish, but then there would be no need to be able to "select" the image.

**Comment by Osndok** [comment]
Stateful "resizing" of images is a bit of a misfeature because it greatly depends on the monitors dpi and available screen size that you are viewing it on. IMO, it would be better to have a constraint based display.

i.e. rather than 
* If the image "fits" within the current viewport, it is displayed native size
* If either of the image dimensions is too large to fit in the viewport, it is minimally scaled down to fit

To do it the way you suggest (with a draggable resize widget) might be nice (if we could save the size in 'ems' relative to the surrounding text), but would be a **LOT** of work.

**Comment by synchr** [comment]
I like that idea since the main reason I'm resizing images is because they doesn't fit in the viewport. Is there already an open issue for that? Otherwise we should probably create one and close this one.

**Comment by Osndok** [comment]
It sorta overlaps with #65 & #315 ... and probably obsoletes [Launchpad-941702](https://bugs.launchpad.net/zim/+bug/941702), but I am not aware of any direct equivalent.

If you feel like the viewport constraint is more inline with your needs, you might be able to just change the title of this issue... however... IIRC, Jaap prefers fresh tickets w/o the discussion noise... so if you don't mind the administrative work (and can think of a really good title) a new ticket might be the better way to go (just include this number in the description to keep everything researchable).

**Comment by synchr** [comment]
I created a new issue with Osndok's suggestion (#324)
