### ISSUE TITLE
Gtk3: index colors hardcoded, must adapt to style

### ISSUE THREAD

**Issue by nelas** [jaap-karssenberg/zim-desktop-wiki#351]
The default dark colorscheme needs some tweaking. For instance, index is not readable and verbatim text is too dark. Colors for headings and links could also be improved.

![screenshot from 2018-02-22 10-49-24](https://user-images.githubusercontent.com/361179/36543801-9e99e7b6-17c3-11e8-8800-4873804094e3.png)

Using the standard Global Dark Theme on Ubuntu GNOME.

Will the colors be handled differently in the Gtk3 port or simply through additional configs?

**Comment by jaap-karssenberg** [comment]
The color of the side panes is a regression
Index pane used default color for existing pages and insensitive state for placeholders.
Broken due to change in style initialization.

Now default color is hardcoded as black and the insensitive color as grey

(Color for the text regions can be configured same way as before)
