### ISSUE TITLE
Change zim note file extension

### ISSUE THREAD

**Issue by tecepe** [jaap-karssenberg/zim-desktop-wiki#378]
Hi,

I often have .txt files that I need to keep out from my notebook because Zim tries to interpret them as subpages instead of attachments.

I could find this [bug report](https://bugs.launchpad.net/zim/+bug/1641268) from 2016.

Is there a way to overcome this situation other then keeping the files in a different place?

**Comment by krisztianmukli** [comment]
I think a better solution could be the introduction of a sort of .zimignore file, similar to .gitignore file.  Further, Zim could automatically ignore files that do not expose the header info in the first line.

Like rjmaris said in https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/306

**Comment by tecepe** [comment]
Thanks, @krisztianmukli . Ignoring files without header sounds like an fast and easy solution to implement. Of course, I'm saying that not knowing much about the code base. The `.zimignore` also seems to be useful, not for this particular case but it would be a very valid resource, in my opinion.

**Comment by krisztianmukli** [comment]
You are welcome @tecepe! Changing file extension and wiki tree structure is a recurring feature request, which I definitely disagree, because it is breaking the existing use cases (or if it is implemented it should be optional). At the same time I admit, using every .txt file as a wiki page is not the expected behaviour. We need an exclude-option. 

By the way, this time you can use as a workaround renaming excluded files to start with an exclamation mark, Zim will not process this files (test.txt -> !test.txt), and it works under ext4 and ntfs too. Unfortunately that files not listed as attachments too...

Check this issue: https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/164 
It is maybe fixed already in next release :-)

**Comment by tecepe** [comment]
Thanks again, @krisztianmukli . The alternative wiki tree structure should be optional, of course. I will add this in the description of that issue. 

Unfortunately the suggested workarounds are not an option for my work flow. I'm glad the ignoring scheme using the file header is in the oven.  I will hold my breath. =)

**Comment by BehindTheBrain** [comment]
This is trivially possible, and already works. Just change /usr/lib/python2.7/site-packages/zimlnotebook/layout.py:   default_extension = '.txt' 

Basic testing suggests that this works just fine, and leaves other text files alone (which is a major issue).

It would be a nice feature to allow a checkbox in zim options to allow the user to switch this default file extension. 

I vote for .zxt as the default.
