### ISSUE TITLE
Deletion of Version Control entries

### ISSUE THREAD

**Issue by sojusnik** [jaap-karssenberg/zim-desktop-wiki#88]
Is there currently a way to manually delete some entries in the Version Control plugin? Over the years I've accumulated a lot of entries, so that opening the Version Control window takes over 15 seconds.

Ideally, there should be some automatic deletion of old entries. Everything over f.i. 2 years could be deleted automatically, except manually labeled ones.

**Comment by jaap-karssenberg** [comment]
No, this is typically not how these version control systems work.

Loading of the dialog we should fix though by allowing for a range to be loaded in

**Comment by Osndok** [comment]
Yes, pagination... I was about to say that too!

However, I think you may have accidentally closed this ticket, as it sounds like a valid bug/need (just change the summary).

**Comment by jaap-karssenberg** [comment]
@Osndok no, I am doing that on purpose, because the main topic of the ticket was a question on deleting old versions. Trying to be a bit "black and white" on tickets, just to prevent getting stuck with hundreds of tickets like happened on the launchpad tracker

**Comment by sojusnik** [comment]
@jaap-karssenberg do you already have this on your personal to-do list or do you plan to open a separate issue?

**Comment by Osndok** [comment]
Be careful @sojusnik, you are *not* entitled to anyone's work here. Not even administrative work. He doesn't have to (and probably wont) open a new ticket for you. Please do whatever you can to take load *off* others.

**Comment by sojusnik** [comment]
@Osndok 

> Be careful @sojusnik, you are not entitled to anyone's work here. Not even administrative work.

I've never had such a claim or anything else in this direction. I was just curious, like you were, why this issue was closed although @jaap-karssenberg mentioned

> Loading of the dialog we should fix though by allowing for a range to be loaded in

It's not a big deal to open a new issue myself. Just wanted to know what Jaap's thoughts are on this issue and how to do it the "proper" way.

**Comment by Osndok** [comment]
Technically, jaap is 100% correct... nobody really **deletes** version control entries.

Perhaps a way to avoid this in the future is to title & describe your reports with the **symptoms** of your problems (e.g. "selecting 'versions...' takes forever to load"), rather than guessing at a solution... which is something I am guilty of too, for sure, though I don't know why I do it.

I think that if you were to open a ticket with the summary "paginate version control entries in 'versions' history view", it might be more helpful, technically correct, still have enough keywords for others to find, and might eventually be accomplished.

**Comment by jaap-karssenberg** [comment]
@sojusnik yes please open a ticket describing the problem - something like "version dialog takes too long to open with long version history" - and a summary of the issue. This would make the issue sufficiently "actionable" that it is clear when it is fixed. 

I stopped keeping a "shadow list" of items I'm working on, because this makes it hard for others to contribute - so if it is not in the tracker with a crisp description it is likely to be forgotten.

Sorry to be picky on this, but I have a bit of a "hangover" of what happened to the launchpad issue list, so trying to improve - if anything to keep my own sanity ...

**Comment by sojusnik** [comment]
@Osndok 
> Perhaps a way to avoid this in the future is to title & describe your reports with the symptoms of your problems (e.g. "selecting 'versions...' takes forever to load"), rather than guessing at a solution... which is something I am guilty of too, for sure, though I don't know why I do it.

I totally agree here. Thanks for pointing that out.

@jaap-karssenberg 
> @sojusnik yes please open a ticket describing the problem - something like "version dialog takes too long to open with long version history" - and a summary of the issue. This would make the issue sufficiently "actionable" that it is clear when it is fixed.

Thanks for clarification! Opened a [new](https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/125) one.
